name: Deploy to EKS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t backend-app ./backend/service1

    - name: Tag Image
      run: |
        docker tag backend-app:latest ${{ secrets.ECR_BACKEND }}

    - name: Push Image to ECR
      run: |
        docker push ${{ secrets.ECR_BACKEND }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name devops-eks

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/base/
        kubectl rollout restart deployment backend-app